# Generated by Django 4.2.11 on 2024-05-09 07:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school14', '0002_alter_news_id_alter_news_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
