# Generated by Django 4.2.11 on 2024-05-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school14', '0003_alter_menuitem_content_alter_news_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('FIO', models.CharField(max_length=150, verbose_name='ФИО учителя')),
                ('foto', models.ImageField(upload_to='media/media/teachers/', verbose_name='Фото учителя')),
                ('pub', models.CharField(max_length=500, verbose_name='Данные учителя')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'ordering': ('FIO',),
            },
        ),
    ]
