# Generated by Django 4.2.11 on 2024-05-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school14', '0004_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='category',
            field=models.CharField(choices=[('руководство', 'руководство'), ('учитель', 'учитель'), ('другое', 'другое')], default='другое', max_length=150),
        ),
        migrations.AddField(
            model_name='teacher',
            name='dolg',
            field=models.CharField(default='другое', max_length=150, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='FIO',
            field=models.CharField(default='другое', max_length=150, verbose_name='ФИО учителя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/media/teachers/', verbose_name='Фото учителя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pub',
            field=models.CharField(default='другое', max_length=500, verbose_name='Данные учителя'),
        ),
    ]
