# Generated by Django 4.2.11 on 2024-05-10 06:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school14', '0005_teacher_category_teacher_dolg_alter_teacher_fio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='FIO',
            field=models.CharField(max_length=150, verbose_name='ФИО учителя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.CharField(choices=[('руководство', 'руководство'), ('учитель', 'учитель'), ('другое', 'другое')], max_length=150),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dolg',
            field=models.CharField(max_length=150, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pub',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=500, verbose_name='Данные учителя'),
        ),
    ]
