# Generated by Django 4.2.11 on 2024-05-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school14', '0006_alter_teacher_fio_alter_teacher_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/media/teachers/', verbose_name='Фото учителя'),
        ),
    ]
