# Generated by Django 4.2.11 on 2024-05-13 13:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school14', '0010_alter_teacher_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='foto',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Фото учителя'),
        ),
    ]
